matrix:
  include:
    ##################################
    # Django tests
    ##################################

    - language: python
      python:
        - "3.5"

      sudo: False

      addons:
          postgresql: "9.6"

      # install dependencies
      install:
          - pip install -r requirements.txt
          - pip install -r test-requirements.txt
          - pip install coveralls

      env: 
          - TEST=True DATABASE_URL=postgres://postgres@localhost/cellcountr_test

      before_script:
          - psql -c 'create database cellcountr_test;' -U postgres
          - npm install -g npm@'>=3'

      # run tests
      script: coverage run --source=cellcounter --omit='*migrations*' manage.py test

      after_success:
          coveralls


    ##################################
    # Integration tests
    ##################################

    - language: python
      python:
        - "3.5"
      node_js:
        - "12.6"

      sudo: False

      addons:
          postgresql: "9.6"

      # install dependencies
      install:
          - pip install -r requirements.txt
          - pip install -r test-requirements.txt
          - npm i -g npm
          - npm install node
          - npm ci --verbose

      env: 
          - DEBUG=True ALLOWED_HOSTS="127.0.0.1" PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin

      before_script:
          - python manage.py migrate

      # run tests
      script: bash test_integration.sh

