language: python
python:
  - "2.7"

# command to install dependencies
install:
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt

env: TEST=True

# command to run tests
script: python manage.py test cellcounter.main cellcounter.cc_kapi cellcounter.accounts
