language: python
python:
  - "2.7"

services: postgresql

# command to install dependencies
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install --allow-all-external -r test-requirements.txt
    - pip install coveralls

env: 
    - TEST=True DATABASE_URL=postgres://postgres@localhost/cellcountr_test

before_script:
    - psql -c 'create database cellcountr_test;' -U postgres

# command to run tests
script: coverage run --source=cellcounter --omit='*migrations*' manage.py test

after_success:
    coveralls
