language: python
python:
  - "2.7"

# command to install dependencies
install:
 - pip install --use-mirrors -r requirements.txt
 - pip install --use-mirrors -r test-requirements.txt

# command to run tests
script: python manage.py test cellcounter.main cellcounter.cc_kapi cellcounter.accounts
