language: python
python:
  - "2.7"

# command to install dependencies
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install --allow-all-external -r test-requirements.txt
    - pip install coveralls

env: TEST=True

# command to run tests
script: coverage run manage.py test cellcounter.main cellcounter.cc_kapi cellcounter.accounts

after_success:
    coveralls
